// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protofiles/antibruteforce.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe3b93af15a686d, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type AuthResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe3b93af15a686d, []int{1}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type DropRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropRequest) Reset()         { *m = DropRequest{} }
func (m *DropRequest) String() string { return proto.CompactTextString(m) }
func (*DropRequest) ProtoMessage()    {}
func (*DropRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe3b93af15a686d, []int{2}
}

func (m *DropRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropRequest.Unmarshal(m, b)
}
func (m *DropRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropRequest.Marshal(b, m, deterministic)
}
func (m *DropRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropRequest.Merge(m, src)
}
func (m *DropRequest) XXX_Size() int {
	return xxx_messageInfo_DropRequest.Size(m)
}
func (m *DropRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DropRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DropRequest proto.InternalMessageInfo

func (m *DropRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *DropRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type DropResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropResponse) Reset()         { *m = DropResponse{} }
func (m *DropResponse) String() string { return proto.CompactTextString(m) }
func (*DropResponse) ProtoMessage()    {}
func (*DropResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe3b93af15a686d, []int{3}
}

func (m *DropResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropResponse.Unmarshal(m, b)
}
func (m *DropResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropResponse.Marshal(b, m, deterministic)
}
func (m *DropResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropResponse.Merge(m, src)
}
func (m *DropResponse) XXX_Size() int {
	return xxx_messageInfo_DropResponse.Size(m)
}
func (m *DropResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DropResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DropResponse proto.InternalMessageInfo

func (m *DropResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type AddToBlacklistRequest struct {
	Subnet               string   `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToBlacklistRequest) Reset()         { *m = AddToBlacklistRequest{} }
func (m *AddToBlacklistRequest) String() string { return proto.CompactTextString(m) }
func (*AddToBlacklistRequest) ProtoMessage()    {}
func (*AddToBlacklistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe3b93af15a686d, []int{4}
}

func (m *AddToBlacklistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToBlacklistRequest.Unmarshal(m, b)
}
func (m *AddToBlacklistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToBlacklistRequest.Marshal(b, m, deterministic)
}
func (m *AddToBlacklistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToBlacklistRequest.Merge(m, src)
}
func (m *AddToBlacklistRequest) XXX_Size() int {
	return xxx_messageInfo_AddToBlacklistRequest.Size(m)
}
func (m *AddToBlacklistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToBlacklistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddToBlacklistRequest proto.InternalMessageInfo

func (m *AddToBlacklistRequest) GetSubnet() string {
	if m != nil {
		return m.Subnet
	}
	return ""
}

type AddToBlacklistResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToBlacklistResponse) Reset()         { *m = AddToBlacklistResponse{} }
func (m *AddToBlacklistResponse) String() string { return proto.CompactTextString(m) }
func (*AddToBlacklistResponse) ProtoMessage()    {}
func (*AddToBlacklistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe3b93af15a686d, []int{5}
}

func (m *AddToBlacklistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToBlacklistResponse.Unmarshal(m, b)
}
func (m *AddToBlacklistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToBlacklistResponse.Marshal(b, m, deterministic)
}
func (m *AddToBlacklistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToBlacklistResponse.Merge(m, src)
}
func (m *AddToBlacklistResponse) XXX_Size() int {
	return xxx_messageInfo_AddToBlacklistResponse.Size(m)
}
func (m *AddToBlacklistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToBlacklistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddToBlacklistResponse proto.InternalMessageInfo

func (m *AddToBlacklistResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type RemoveFromBlacklistRequest struct {
	Subnet               string   `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFromBlacklistRequest) Reset()         { *m = RemoveFromBlacklistRequest{} }
func (m *RemoveFromBlacklistRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFromBlacklistRequest) ProtoMessage()    {}
func (*RemoveFromBlacklistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe3b93af15a686d, []int{6}
}

func (m *RemoveFromBlacklistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFromBlacklistRequest.Unmarshal(m, b)
}
func (m *RemoveFromBlacklistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFromBlacklistRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFromBlacklistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFromBlacklistRequest.Merge(m, src)
}
func (m *RemoveFromBlacklistRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFromBlacklistRequest.Size(m)
}
func (m *RemoveFromBlacklistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFromBlacklistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFromBlacklistRequest proto.InternalMessageInfo

func (m *RemoveFromBlacklistRequest) GetSubnet() string {
	if m != nil {
		return m.Subnet
	}
	return ""
}

type RemoveFromBlacklistResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFromBlacklistResponse) Reset()         { *m = RemoveFromBlacklistResponse{} }
func (m *RemoveFromBlacklistResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveFromBlacklistResponse) ProtoMessage()    {}
func (*RemoveFromBlacklistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe3b93af15a686d, []int{7}
}

func (m *RemoveFromBlacklistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFromBlacklistResponse.Unmarshal(m, b)
}
func (m *RemoveFromBlacklistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFromBlacklistResponse.Marshal(b, m, deterministic)
}
func (m *RemoveFromBlacklistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFromBlacklistResponse.Merge(m, src)
}
func (m *RemoveFromBlacklistResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveFromBlacklistResponse.Size(m)
}
func (m *RemoveFromBlacklistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFromBlacklistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFromBlacklistResponse proto.InternalMessageInfo

func (m *RemoveFromBlacklistResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type AddToWhitelistRequest struct {
	Subnet               string   `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToWhitelistRequest) Reset()         { *m = AddToWhitelistRequest{} }
func (m *AddToWhitelistRequest) String() string { return proto.CompactTextString(m) }
func (*AddToWhitelistRequest) ProtoMessage()    {}
func (*AddToWhitelistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe3b93af15a686d, []int{8}
}

func (m *AddToWhitelistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToWhitelistRequest.Unmarshal(m, b)
}
func (m *AddToWhitelistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToWhitelistRequest.Marshal(b, m, deterministic)
}
func (m *AddToWhitelistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToWhitelistRequest.Merge(m, src)
}
func (m *AddToWhitelistRequest) XXX_Size() int {
	return xxx_messageInfo_AddToWhitelistRequest.Size(m)
}
func (m *AddToWhitelistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToWhitelistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddToWhitelistRequest proto.InternalMessageInfo

func (m *AddToWhitelistRequest) GetSubnet() string {
	if m != nil {
		return m.Subnet
	}
	return ""
}

type AddToWhitelistResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToWhitelistResponse) Reset()         { *m = AddToWhitelistResponse{} }
func (m *AddToWhitelistResponse) String() string { return proto.CompactTextString(m) }
func (*AddToWhitelistResponse) ProtoMessage()    {}
func (*AddToWhitelistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe3b93af15a686d, []int{9}
}

func (m *AddToWhitelistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToWhitelistResponse.Unmarshal(m, b)
}
func (m *AddToWhitelistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToWhitelistResponse.Marshal(b, m, deterministic)
}
func (m *AddToWhitelistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToWhitelistResponse.Merge(m, src)
}
func (m *AddToWhitelistResponse) XXX_Size() int {
	return xxx_messageInfo_AddToWhitelistResponse.Size(m)
}
func (m *AddToWhitelistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToWhitelistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddToWhitelistResponse proto.InternalMessageInfo

func (m *AddToWhitelistResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type RemoveFromWhitelistRequest struct {
	Subnet               string   `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFromWhitelistRequest) Reset()         { *m = RemoveFromWhitelistRequest{} }
func (m *RemoveFromWhitelistRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFromWhitelistRequest) ProtoMessage()    {}
func (*RemoveFromWhitelistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe3b93af15a686d, []int{10}
}

func (m *RemoveFromWhitelistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFromWhitelistRequest.Unmarshal(m, b)
}
func (m *RemoveFromWhitelistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFromWhitelistRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFromWhitelistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFromWhitelistRequest.Merge(m, src)
}
func (m *RemoveFromWhitelistRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFromWhitelistRequest.Size(m)
}
func (m *RemoveFromWhitelistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFromWhitelistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFromWhitelistRequest proto.InternalMessageInfo

func (m *RemoveFromWhitelistRequest) GetSubnet() string {
	if m != nil {
		return m.Subnet
	}
	return ""
}

type RemoveFromWhitelistResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFromWhitelistResponse) Reset()         { *m = RemoveFromWhitelistResponse{} }
func (m *RemoveFromWhitelistResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveFromWhitelistResponse) ProtoMessage()    {}
func (*RemoveFromWhitelistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe3b93af15a686d, []int{11}
}

func (m *RemoveFromWhitelistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFromWhitelistResponse.Unmarshal(m, b)
}
func (m *RemoveFromWhitelistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFromWhitelistResponse.Marshal(b, m, deterministic)
}
func (m *RemoveFromWhitelistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFromWhitelistResponse.Merge(m, src)
}
func (m *RemoveFromWhitelistResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveFromWhitelistResponse.Size(m)
}
func (m *RemoveFromWhitelistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFromWhitelistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFromWhitelistResponse proto.InternalMessageInfo

func (m *RemoveFromWhitelistResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "schema.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "schema.AuthResponse")
	proto.RegisterType((*DropRequest)(nil), "schema.DropRequest")
	proto.RegisterType((*DropResponse)(nil), "schema.DropResponse")
	proto.RegisterType((*AddToBlacklistRequest)(nil), "schema.AddToBlacklistRequest")
	proto.RegisterType((*AddToBlacklistResponse)(nil), "schema.AddToBlacklistResponse")
	proto.RegisterType((*RemoveFromBlacklistRequest)(nil), "schema.RemoveFromBlacklistRequest")
	proto.RegisterType((*RemoveFromBlacklistResponse)(nil), "schema.RemoveFromBlacklistResponse")
	proto.RegisterType((*AddToWhitelistRequest)(nil), "schema.AddToWhitelistRequest")
	proto.RegisterType((*AddToWhitelistResponse)(nil), "schema.AddToWhitelistResponse")
	proto.RegisterType((*RemoveFromWhitelistRequest)(nil), "schema.RemoveFromWhitelistRequest")
	proto.RegisterType((*RemoveFromWhitelistResponse)(nil), "schema.RemoveFromWhitelistResponse")
}

func init() { proto.RegisterFile("protofiles/antibruteforce.proto", fileDescriptor_ffe3b93af15a686d) }

var fileDescriptor_ffe3b93af15a686d = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x51, 0x4f, 0xc2, 0x30,
	0x14, 0x85, 0x61, 0x08, 0xc1, 0x8b, 0xe1, 0xa1, 0x20, 0x21, 0x33, 0xa2, 0x29, 0x2f, 0xbc, 0x08,
	0x89, 0xf8, 0x07, 0x20, 0xc6, 0x57, 0xe3, 0x62, 0x62, 0xe2, 0x93, 0x03, 0x8a, 0x34, 0x8c, 0xdd,
	0xda, 0x76, 0xfa, 0x87, 0xfd, 0x21, 0x66, 0x2b, 0x8c, 0x31, 0x36, 0xc0, 0xc7, 0xf6, 0xf6, 0x7c,
	0xf7, 0x64, 0xe7, 0x64, 0x70, 0x23, 0x24, 0x6a, 0x9c, 0x73, 0x8f, 0xa9, 0x81, 0xeb, 0x6b, 0x3e,
	0x91, 0x81, 0x66, 0x73, 0x94, 0x53, 0xd6, 0x8f, 0x26, 0xa4, 0xa2, 0xa6, 0x0b, 0xb6, 0x72, 0xe9,
	0x33, 0xd4, 0x46, 0x81, 0x5e, 0x38, 0xec, 0x2b, 0x60, 0x4a, 0x93, 0x26, 0x94, 0x3d, 0xfc, 0xe4,
	0x7e, 0xbb, 0x78, 0x5b, 0xec, 0x9d, 0x3b, 0xe6, 0x40, 0x6c, 0xa8, 0x0a, 0x57, 0xa9, 0x1f, 0x94,
	0xb3, 0xb6, 0x15, 0x0d, 0xe2, 0x33, 0xa9, 0x83, 0xc5, 0x45, 0xbb, 0x14, 0xdd, 0x5a, 0x5c, 0xd0,
	0x0e, 0x5c, 0x18, 0xa0, 0x12, 0xe8, 0x2b, 0x16, 0xce, 0x71, 0x19, 0xe1, 0xaa, 0x8e, 0x85, 0x4b,
	0x3a, 0x84, 0xda, 0xa3, 0x44, 0x71, 0x78, 0xa1, 0x81, 0x5a, 0x49, 0xa8, 0x11, 0xe5, 0x40, 0x07,
	0x70, 0x39, 0x9a, 0xcd, 0x5e, 0x71, 0xec, 0xb9, 0xd3, 0xa5, 0xc7, 0x95, 0xde, 0xe0, 0x5b, 0x50,
	0x51, 0xc1, 0xc4, 0x67, 0x7a, 0xcd, 0x5f, 0x9f, 0x68, 0x0f, 0x5a, 0x69, 0x41, 0x0e, 0xfa, 0x01,
	0x6c, 0x87, 0xad, 0xf0, 0x9b, 0x3d, 0x49, 0x5c, 0x9d, 0xcc, 0xbf, 0x83, 0xab, 0x4c, 0xd5, 0x11,
	0xff, 0x6f, 0x0b, 0xae, 0xd9, 0x7f, 0xfc, 0x27, 0x04, 0xa7, 0xf8, 0x3f, 0x99, 0xbf, 0xe3, 0xff,
	0xe8, 0x92, 0xfb, 0xdf, 0x12, 0xd4, 0x47, 0xbe, 0xe6, 0xe3, 0xb8, 0x66, 0x64, 0x08, 0x67, 0x61,
	0x0f, 0x48, 0xa3, 0x6f, 0x9a, 0xd6, 0x4f, 0xd4, 0xcc, 0x6e, 0xee, 0x5e, 0x1a, 0x2a, 0x2d, 0x84,
	0xa2, 0x30, 0xe7, 0xad, 0x28, 0x51, 0x95, 0xad, 0x28, 0x59, 0x05, 0x5a, 0x20, 0x2f, 0x50, 0xdf,
	0xcd, 0x92, 0x5c, 0xc7, 0xf8, 0xac, 0x52, 0xd8, 0x9d, 0xbc, 0x71, 0x8c, 0xfc, 0x80, 0x46, 0x46,
	0x7c, 0x84, 0x6e, 0x84, 0xf9, 0x8d, 0xb0, 0xbb, 0x07, 0xdf, 0xec, 0x99, 0x8e, 0xbf, 0x6d, 0xca,
	0x74, 0x3a, 0xa9, 0x94, 0xe9, 0xbd, 0x48, 0xd2, 0xa6, 0xb7, 0xdc, 0x0c, 0xd3, 0x7b, 0xf0, 0xee,
	0xc1, 0x37, 0x9b, 0x0d, 0xe3, 0xf2, 0x7b, 0xc9, 0x15, 0x7c, 0x52, 0x89, 0x7e, 0x21, 0xc3, 0xbf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0x77, 0x90, 0xa3, 0x65, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AntiBruteforceClient is the client API for AntiBruteforce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AntiBruteforceClient interface {
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Drop(ctx context.Context, in *DropRequest, opts ...grpc.CallOption) (*DropResponse, error)
	AddToBlacklist(ctx context.Context, in *AddToBlacklistRequest, opts ...grpc.CallOption) (*AddToBlacklistResponse, error)
	RemoveFromBlacklist(ctx context.Context, in *RemoveFromBlacklistRequest, opts ...grpc.CallOption) (*RemoveFromBlacklistResponse, error)
	AddToWhitelist(ctx context.Context, in *AddToWhitelistRequest, opts ...grpc.CallOption) (*AddToWhitelistResponse, error)
	RemoveFromWhitelist(ctx context.Context, in *RemoveFromWhitelistRequest, opts ...grpc.CallOption) (*RemoveFromWhitelistResponse, error)
}

type antiBruteforceClient struct {
	cc *grpc.ClientConn
}

func NewAntiBruteforceClient(cc *grpc.ClientConn) AntiBruteforceClient {
	return &antiBruteforceClient{cc}
}

func (c *antiBruteforceClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/schema.AntiBruteforce/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) Drop(ctx context.Context, in *DropRequest, opts ...grpc.CallOption) (*DropResponse, error) {
	out := new(DropResponse)
	err := c.cc.Invoke(ctx, "/schema.AntiBruteforce/Drop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) AddToBlacklist(ctx context.Context, in *AddToBlacklistRequest, opts ...grpc.CallOption) (*AddToBlacklistResponse, error) {
	out := new(AddToBlacklistResponse)
	err := c.cc.Invoke(ctx, "/schema.AntiBruteforce/AddToBlacklist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) RemoveFromBlacklist(ctx context.Context, in *RemoveFromBlacklistRequest, opts ...grpc.CallOption) (*RemoveFromBlacklistResponse, error) {
	out := new(RemoveFromBlacklistResponse)
	err := c.cc.Invoke(ctx, "/schema.AntiBruteforce/RemoveFromBlacklist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) AddToWhitelist(ctx context.Context, in *AddToWhitelistRequest, opts ...grpc.CallOption) (*AddToWhitelistResponse, error) {
	out := new(AddToWhitelistResponse)
	err := c.cc.Invoke(ctx, "/schema.AntiBruteforce/AddToWhitelist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) RemoveFromWhitelist(ctx context.Context, in *RemoveFromWhitelistRequest, opts ...grpc.CallOption) (*RemoveFromWhitelistResponse, error) {
	out := new(RemoveFromWhitelistResponse)
	err := c.cc.Invoke(ctx, "/schema.AntiBruteforce/RemoveFromWhitelist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AntiBruteforceServer is the server API for AntiBruteforce service.
type AntiBruteforceServer interface {
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
	Drop(context.Context, *DropRequest) (*DropResponse, error)
	AddToBlacklist(context.Context, *AddToBlacklistRequest) (*AddToBlacklistResponse, error)
	RemoveFromBlacklist(context.Context, *RemoveFromBlacklistRequest) (*RemoveFromBlacklistResponse, error)
	AddToWhitelist(context.Context, *AddToWhitelistRequest) (*AddToWhitelistResponse, error)
	RemoveFromWhitelist(context.Context, *RemoveFromWhitelistRequest) (*RemoveFromWhitelistResponse, error)
}

// UnimplementedAntiBruteforceServer can be embedded to have forward compatible implementations.
type UnimplementedAntiBruteforceServer struct {
}

func (*UnimplementedAntiBruteforceServer) Auth(ctx context.Context, req *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedAntiBruteforceServer) Drop(ctx context.Context, req *DropRequest) (*DropResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Drop not implemented")
}
func (*UnimplementedAntiBruteforceServer) AddToBlacklist(ctx context.Context, req *AddToBlacklistRequest) (*AddToBlacklistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToBlacklist not implemented")
}
func (*UnimplementedAntiBruteforceServer) RemoveFromBlacklist(ctx context.Context, req *RemoveFromBlacklistRequest) (*RemoveFromBlacklistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromBlacklist not implemented")
}
func (*UnimplementedAntiBruteforceServer) AddToWhitelist(ctx context.Context, req *AddToWhitelistRequest) (*AddToWhitelistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToWhitelist not implemented")
}
func (*UnimplementedAntiBruteforceServer) RemoveFromWhitelist(ctx context.Context, req *RemoveFromWhitelistRequest) (*RemoveFromWhitelistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromWhitelist not implemented")
}

func RegisterAntiBruteforceServer(s *grpc.Server, srv AntiBruteforceServer) {
	s.RegisterService(&_AntiBruteforce_serviceDesc, srv)
}

func _AntiBruteforce_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.AntiBruteforce/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_Drop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).Drop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.AntiBruteforce/Drop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).Drop(ctx, req.(*DropRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_AddToBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).AddToBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.AntiBruteforce/AddToBlacklist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).AddToBlacklist(ctx, req.(*AddToBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_RemoveFromBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).RemoveFromBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.AntiBruteforce/RemoveFromBlacklist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).RemoveFromBlacklist(ctx, req.(*RemoveFromBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_AddToWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToWhitelistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).AddToWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.AntiBruteforce/AddToWhitelist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).AddToWhitelist(ctx, req.(*AddToWhitelistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_RemoveFromWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromWhitelistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).RemoveFromWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.AntiBruteforce/RemoveFromWhitelist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).RemoveFromWhitelist(ctx, req.(*RemoveFromWhitelistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AntiBruteforce_serviceDesc = grpc.ServiceDesc{
	ServiceName: "schema.AntiBruteforce",
	HandlerType: (*AntiBruteforceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _AntiBruteforce_Auth_Handler,
		},
		{
			MethodName: "Drop",
			Handler:    _AntiBruteforce_Drop_Handler,
		},
		{
			MethodName: "AddToBlacklist",
			Handler:    _AntiBruteforce_AddToBlacklist_Handler,
		},
		{
			MethodName: "RemoveFromBlacklist",
			Handler:    _AntiBruteforce_RemoveFromBlacklist_Handler,
		},
		{
			MethodName: "AddToWhitelist",
			Handler:    _AntiBruteforce_AddToWhitelist_Handler,
		},
		{
			MethodName: "RemoveFromWhitelist",
			Handler:    _AntiBruteforce_RemoveFromWhitelist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protofiles/antibruteforce.proto",
}
