version: '3.7'

services:
  integration_tests:
    build:
      context: ../..
      dockerfile: docker/integr_test/Dockerfile
    command: "true"
    networks:
      - db
      - antibruteforce
    environment:
      GRPC_SERVICE: "antibruteforce:8080"
    depends_on:
      - antibruteforce
  antibruteforce:
    build:
      context: ../..
      dockerfile: docker/service/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ../../config.yml:/opt/antibruteforce/config.yaml
    networks:
      - db
      - antibruteforce
    depends_on:
      - db
    restart: on-failure
  db:
    image: "postgres:11-alpine"
    environment:
      - POSTGRES_USER=antibruteforce
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=antibruteforce
    ports:
      - "5432:5432"
    volumes:
      - ../../db/migrations/001.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db
networks:
  db:
    driver: bridge
  antibruteforce:
    driver: bridge
